# goals.append(naviagator.getPoseStamped([-1.5, 0.0], 0  ))
#     goals.append(naviagator.getPoseStamped([-1.5, 0.0], 45 ))
#     goals.append(naviagator.getPoseStamped([-1.5, 0.0], 90 ))
#     goals.append(naviagator.getPoseStamped([-1.5, 0.0], 135))
#     goals.append(naviagator.getPoseStamped([-1.5, 0.0], 180))
#     goals.append(naviagator.getPoseStamped([-1.5, 0.0], 225))
#     goals.append(naviagator.getPoseStamped([-1.5, 0.0], 270))
#     goals.append(naviagator.getPoseStamped([-1.5, 0.0], 315))

#     goals.append(naviagator.getPoseStamped([-0.3, -0.5], 0  ))
#     goals.append(naviagator.getPoseStamped([-0.3, -0.5], 45 ))
#     goals.append(naviagator.getPoseStamped([-0.3, -0.5], 90 ))
#     goals.append(naviagator.getPoseStamped([-0.3, -0.5], 135))
#     goals.append(naviagator.getPoseStamped([-0.3, -0.5], 180))
#     goals.append(naviagator.getPoseStamped([-0.3, -0.5], 225))
#     goals.append(naviagator.getPoseStamped([-0.3, -0.5], 270))
#     goals.append(naviagator.getPoseStamped([-0.3, -0.5], 315))

#     goals.append(naviagator.getPoseStamped([-1.5, -1.0], 0  ))
#     goals.append(naviagator.getPoseStamped([-1.5, -1.0], 45 ))
#     goals.append(naviagator.getPoseStamped([-1.5, -1.0], 90 ))
#     goals.append(naviagator.getPoseStamped([-1.5, -1.0], 135))
#     goals.append(naviagator.getPoseStamped([-1.5, -1.0], 180))
#     goals.append(naviagator.getPoseStamped([-1.5, -1.0], 225))
#     goals.append(naviagator.getPoseStamped([-1.5, -1.0], 270))
#     goals.append(naviagator.getPoseStamped([-1.5, -1.0], 315))


#     goals.append(naviagator.getPoseStamped([-0.3, -1.5], 0  ))
#     goals.append(naviagator.getPoseStamped([-0.3, -1.5], 45 ))
#     goals.append(naviagator.getPoseStamped([-0.3, -1.5], 90 ))
#     goals.append(naviagator.getPoseStamped([-0.3, -1.5], 135))
#     goals.append(naviagator.getPoseStamped([-0.3, -1.5], 180))
#     goals.append(naviagator.getPoseStamped([-0.3, -1.5], 225))
#     goals.append(naviagator.getPoseStamped([-0.3, -1.5], 270))
#     goals.append(naviagator.getPoseStamped([-0.3, -1.5], 315))


#     goals.append(naviagator.getPoseStamped([-1.5, -2.0], 0  ))
#     goals.append(naviagator.getPoseStamped([-1.5, -2.0], 45 ))
#     goals.append(naviagator.getPoseStamped([-1.5, -2.0], 90 ))
#     goals.append(naviagator.getPoseStamped([-1.5, -2.0], 135))
#     goals.append(naviagator.getPoseStamped([-1.5, -2.0], 180))
#     goals.append(naviagator.getPoseStamped([-1.5, -2.0], 225))
#     goals.append(naviagator.getPoseStamped([-1.5, -2.0], 270))
#     goals.append(naviagator.getPoseStamped([-1.5, -2.0], 315))


#     goals.append(naviagator.getPoseStamped([-0.3, -2.5], 0  ))
#     goals.append(naviagator.getPoseStamped([-0.3, -2.5], 45 ))
#     goals.append(naviagator.getPoseStamped([-0.3, -2.5], 90 ))
#     goals.append(naviagator.getPoseStamped([-0.3, -2.5], 135))
#     goals.append(naviagator.getPoseStamped([-0.3, -2.5], 180))
#     goals.append(naviagator.getPoseStamped([-0.3, -2.5], 225))
#     goals.append(naviagator.getPoseStamped([-0.3, -2.5], 270))
#     goals.append(naviagator.getPoseStamped([-0.3, -2.5], 315))


#     goals.append(naviagator.getPoseStamped([-1.5, -3.0], 0  ))
#     goals.append(naviagator.getPoseStamped([-1.5, -3.0], 45 ))
#     goals.append(naviagator.getPoseStamped([-1.5, -3.0], 90 ))
#     goals.append(naviagator.getPoseStamped([-1.5, -3.0], 135))
#     goals.append(naviagator.getPoseStamped([-1.5, -3.0], 180))
#     goals.append(naviagator.getPoseStamped([-1.5, -3.0], 225))
#     goals.append(naviagator.getPoseStamped([-1.5, -3.0], 270))
#     goals.append(naviagator.getPoseStamped([-1.5, -3.0], 315))

    
#     goals.append(naviagator.getPoseStamped([-0.3, -3.5], 0  ))
#     goals.append(naviagator.getPoseStamped([-0.3, -3.5], 45 ))
#     goals.append(naviagator.getPoseStamped([-0.3, -3.5], 90 ))
#     goals.append(naviagator.getPoseStamped([-0.3, -3.5], 135))
#     goals.append(naviagator.getPoseStamped([-0.3, -3.5], 180))
#     goals.append(naviagator.getPoseStamped([-0.3, -3.5], 225))
#     goals.append(naviagator.getPoseStamped([-0.3, -3.5], 270))
#     goals.append(naviagator.getPoseStamped([-0.3, -3.5], 315))


#     goals.append(naviagator.getPoseStamped([-1.5, -4.0], 0  ))
#     goals.append(naviagator.getPoseStamped([-1.5, -4.0], 45 ))
#     goals.append(naviagator.getPoseStamped([-1.5, -4.0], 90 ))
#     goals.append(naviagator.getPoseStamped([-1.5, -4.0], 135))
#     goals.append(naviagator.getPoseStamped([-1.5, -4.0], 180))
#     goals.append(naviagator.getPoseStamped([-1.5, -4.0], 225))
#     goals.append(naviagator.getPoseStamped([-1.5, -4.0], 270))
#     goals.append(naviagator.getPoseStamped([-1.5, -4.0], 315))


#     goals.append(naviagator.getPoseStamped([-0.3, -4.5], 0  ))
#     goals.append(naviagator.getPoseStamped([-0.3, -4.5], 45 ))
#     goals.append(naviagator.getPoseStamped([-0.3, -4.5], 90 ))
#     goals.append(naviagator.getPoseStamped([-0.3, -4.5], 135))
#     goals.append(naviagator.getPoseStamped([-0.3, -4.5], 180))
#     goals.append(naviagator.getPoseStamped([-0.3, -4.5], 225))
#     goals.append(naviagator.getPoseStamped([-0.3, -4.5], 270))
#     goals.append(naviagator.getPoseStamped([-0.3, -4.5], 315))


#     goals.append(naviagator.getPoseStamped([-1.5, -5.0], 0  ))
#     goals.append(naviagator.getPoseStamped([-0.3, -5.0], 45 ))
#     goals.append(naviagator.getPoseStamped([-0.3, -5.0], 90 ))
#     goals.append(naviagator.getPoseStamped([-0.3, -5.0], 135))
#     goals.append(naviagator.getPoseStamped([-0.3, -5.0], 180))
#     goals.append(naviagator.getPoseStamped([-0.3, -5.0], 225))
#     goals.append(naviagator.getPoseStamped([-0.3, -5.0], 270))
#     goals.append(naviagator.getPoseStamped([-0.3, -5.0], 315))


#     goals.append(naviagator.getPoseStamped([-1.5, -4.5], 0  ))
#     goals.append(naviagator.getPoseStamped([-1.5, -4.5], 45 ))
#     goals.append(naviagator.getPoseStamped([-1.5, -4.5], 90 ))
#     goals.append(naviagator.getPoseStamped([-1.5, -4.5], 135))
#     goals.append(naviagator.getPoseStamped([-1.5, -4.5], 180))
#     goals.append(naviagator.getPoseStamped([-1.5, -4.5], 225))
#     goals.append(naviagator.getPoseStamped([-1.5, -4.5], 270))
#     goals.append(naviagator.getPoseStamped([-1.5, -4.5], 315))


#     goals.append(naviagator.getPoseStamped([-0.3, -4.0], 0  ))
#     goals.append(naviagator.getPoseStamped([-0.3, -4.0], 45 ))
#     goals.append(naviagator.getPoseStamped([-0.3, -4.0], 90 ))
#     goals.append(naviagator.getPoseStamped([-0.3, -4.0], 135))
#     goals.append(naviagator.getPoseStamped([-0.3, -4.0], 180))
#     goals.append(naviagator.getPoseStamped([-0.3, -4.0], 225))
#     goals.append(naviagator.getPoseStamped([-0.3, -4.0], 270))
#     goals.append(naviagator.getPoseStamped([-0.3, -4.0], 315))


#     goals.append(naviagator.getPoseStamped([-1.5, -3.5], 0  ))
#     goals.append(naviagator.getPoseStamped([-1.5, -3.5], 45 ))
#     goals.append(naviagator.getPoseStamped([-1.5, -3.5], 90 ))
#     goals.append(naviagator.getPoseStamped([-1.5, -3.5], 135))
#     goals.append(naviagator.getPoseStamped([-1.5, -3.5], 180))
#     goals.append(naviagator.getPoseStamped([-1.5, -3.5], 225))
#     goals.append(naviagator.getPoseStamped([-1.5, -3.5], 270))
#     goals.append(naviagator.getPoseStamped([-1.5, -3.5], 315))


#     goals.append(naviagator.getPoseStamped([-0.3, -3.0], 0  ))
#     goals.append(naviagator.getPoseStamped([-0.3, -3.0], 45 ))
#     goals.append(naviagator.getPoseStamped([-0.3, -3.0], 90 ))
#     goals.append(naviagator.getPoseStamped([-0.3, -3.0], 135))
#     goals.append(naviagator.getPoseStamped([-0.3, -3.0], 180))
#     goals.append(naviagator.getPoseStamped([-0.3, -3.0], 225))
#     goals.append(naviagator.getPoseStamped([-0.3, -3.0], 270))
#     goals.append(naviagator.getPoseStamped([-0.3, -3.0], 315))


#     goals.append(naviagator.getPoseStamped([-1.5, -2.5], 0  ))
#     goals.append(naviagator.getPoseStamped([-1.5, -2.5], 45 ))
#     goals.append(naviagator.getPoseStamped([-1.5, -2.5], 90 ))
#     goals.append(naviagator.getPoseStamped([-1.5, -2.5], 135))
#     goals.append(naviagator.getPoseStamped([-1.5, -2.5], 180))
#     goals.append(naviagator.getPoseStamped([-1.5, -2.5], 225))
#     goals.append(naviagator.getPoseStamped([-1.5, -2.5], 270))
#     goals.append(naviagator.getPoseStamped([-1.5, -2.5], 315))


#     goals.append(naviagator.getPoseStamped([-0.3, -2.0], 0  ))
#     goals.append(naviagator.getPoseStamped([-0.3, -2.0], 45 ))
#     goals.append(naviagator.getPoseStamped([-0.3, -2.0], 90 ))
#     goals.append(naviagator.getPoseStamped([-0.3, -2.0], 135))
#     goals.append(naviagator.getPoseStamped([-0.3, -2.0], 180))
#     goals.append(naviagator.getPoseStamped([-0.3, -2.0], 225))
#     goals.append(naviagator.getPoseStamped([-0.3, -2.0], 270))
#     goals.append(naviagator.getPoseStamped([-0.3, -2.0], 315))


#     goals.append(naviagator.getPoseStamped([-1.5, -1.5], 0  ))
#     goals.append(naviagator.getPoseStamped([-1.5, -1.5], 45 ))
#     goals.append(naviagator.getPoseStamped([-1.5, -1.5], 90 ))
#     goals.append(naviagator.getPoseStamped([-1.5, -1.5], 135))
#     goals.append(naviagator.getPoseStamped([-1.5, -1.5], 180))
#     goals.append(naviagator.getPoseStamped([-1.5, -1.5], 225))
#     goals.append(naviagator.getPoseStamped([-1.5, -1.5], 270))
#     goals.append(naviagator.getPoseStamped([-1.5, -1.5], 315))


#     goals.append(naviagator.getPoseStamped([-0.3, -1.0], 0  ))
#     goals.append(naviagator.getPoseStamped([-0.3, -1.0], 45 ))
#     goals.append(naviagator.getPoseStamped([-0.3, -1.0], 90 ))
#     goals.append(naviagator.getPoseStamped([-0.3, -1.0], 135))
#     goals.append(naviagator.getPoseStamped([-0.3, -1.0], 180))
#     goals.append(naviagator.getPoseStamped([-0.3, -1.0], 225))
#     goals.append(naviagator.getPoseStamped([-0.3, -1.0], 270))
#     goals.append(naviagator.getPoseStamped([-0.3, -1.0], 315))


#     goals.append(naviagator.getPoseStamped([-1.5, -0.5], 0  ))
#     goals.append(naviagator.getPoseStamped([-1.5, -0.5], 45 ))
#     goals.append(naviagator.getPoseStamped([-1.5, -0.5], 90 ))
#     goals.append(naviagator.getPoseStamped([-1.5, -0.5], 135))
#     goals.append(naviagator.getPoseStamped([-1.5, -0.5], 180))
#     goals.append(naviagator.getPoseStamped([-1.5, -0.5], 225))
#     goals.append(naviagator.getPoseStamped([-1.5, -0.5], 270))
#     goals.append(naviagator.getPoseStamped([-1.5, -0.5], 315))

#     goals.append(naviagator.getPoseStamped([-0.3, 0.0], 0  ))
#     goals.append(naviagator.getPoseStamped([-0.3, 0.0], 45 ))
#     goals.append(naviagator.getPoseStamped([-0.3, 0.0], 90 ))
#     goals.append(naviagator.getPoseStamped([-0.3, 0.0], 135))
#     goals.append(naviagator.getPoseStamped([-0.3, 0.0], 180))
#     goals.append(naviagator.getPoseStamped([-0.3, 0.0], 225))
#     goals.append(naviagator.getPoseStamped([-0.3, 0.0], 270))
#     goals.append(naviagator.getPoseStamped([-0.3, 0.0], 315))