/oakd:
  ros__parameters:
    camera:
      i_enable_imu: false
      i_enable_ir: true
      i_floodlight_brightness: 0
      i_laser_dot_brightness: 720
      i_nn_type: none
      i_pipeline_type: RGBD
      i_usb_speed: SUPER_PLUS
    rgb:
      r_set_man_focus: true
      r_focus: 120
      r_set_man_exposure: true
      r_exposure: 2500
      r_set_man_whitebalance: true
      r_whitebalance: 4800
      i_board_socket_id: 0
      i_fps: 5.0
      i_interleaved: false
      i_max_q_size: 10
      i_preview_size: 250
      i_enable_preview: true
      i_low_bandwidth: false
      i_keep_preview_aspect_ratio: true
      i_publish_topic: true
      i_resolution: 1080P
      #i_width: 1280
      #i_height: 720
      i_set_isp_scale: false
      #i_fsync_continuous: true
      i_fsync_mode: INPUT
      #i_fsync_trigger: true
    stereo:
      i_align_depth: true
      i_publish_topic: true
      i_depth_filter_size: 5
      #i_depth_preset: HIGH_ACCURACY
      #i_disparity_width: DISPARITY_96
      i_enable_brightness_filter: false
      i_enable_speckle_filter: false
      i_enable_temporal_filter: false
      i_publish_confidence: true
      i_lr_check: false
      i_subpixel: false
      i_extended_disp: false
    right:
      i_fps: 5.0
      i_publish_topic: false
      i_fsync_mode: OUTPUT
      #i_fsync_continuous: true
    left:
      i_fps: 5.0
      i_publish_topic: false
      #i_fsync_mode: OUTPUT
      #i_fsync_trigger: true
      #i_fsync_continuous: true
      i_fsync_mode: INPUT
    use_sim_time: false
