/recorder:
  ros__parameters:
    use_sim_time: false
    record:
      all_topics: false
      topics: ["/oakd_cam_B/rgb/camera_info", "/oakd_cam_B/rgb/image_raw", "/oakd_cam_B/stereo/camera_info", "/oakd_cam_B/stereo/confidence", "/oakd_cam_B/stereo/image_raw"]
      is_discovery_disabled: true
      topic_polling_interval:
        sec: 0
        nsec: 10000000
      include_hidden_topics: false
      ignore_leaf_topics: false
      start_paused: true
      disable_keyboard_controls: true

    storage:
      uri: "/tmp"
      storage_id: "sqlite3"
      max_cache_size: 20000000